### ISSUE TITLE
Vial Firmware fails to build 

### ISSUE THREAD

**Issue by tonykakuuu** [mohoyt/lagom#3]
Running  `qmk flash -c -kb sthlmkb/lagom -km vial` fails to build. 

```
Generating: .build/obj_sthlmkb_lagom_vial/src/default_keyboard.h                                    [OK]
Compiling: keyboards/sthlmkb/lagom/matrix.c                                                        In file included from <command-line>:0:0:
./keyboards/sthlmkb/lagom/keymaps/vial/config.h:6:0: error: "ENCODERS_PAD_A" redefined [-Werror]
 #define ENCODERS_PAD_A { C6, F5 }
 ^
In file included from <command-line>:0:0:
./.build/obj_sthlmkb_lagom_vial/src/info_config.h:57:0: note: this is the location of the previous definition
 #    define ENCODERS_PAD_A { D4, F4 }
 ^
In file included from <command-line>:0:0:
./keyboards/sthlmkb/lagom/keymaps/vial/config.h:7:0: error: "ENCODERS_PAD_B" redefined [-Werror]
 #define ENCODERS_PAD_B { D4, F4 }
 ^
In file included from <command-line>:0:0:
./.build/obj_sthlmkb_lagom_vial/src/info_config.h:61:0: note: this is the location of the previous definition
 #    define ENCODERS_PAD_B { C6, F5 }
 ^
cc1: all warnings being treated as errors
 [ERRORS]
 | 
 | 
 | 
gmake[1]: *** [builddefs/common_rules.mk:361: .build/obj_sthlmkb_lagom_vial/matrix.o] Error 1
Make finished with errors
gmake: *** [Makefile:392: sthlmkb/lagom:vial:flash] Error 1
```

Commenting out the `ENCODERS_PAD_A` and B definition lets it at least build without errors but I'm not sure it works, as the keyboard is not recognized by VIAL.

**Comment by mohoyt** [comment]
A couple things:
- Are you building with the vial fork of qmk? 
- I think the error is caused by conflicting definitions of which is encoder pad A and encoder pad B, try swapping the values in one of the places so they match and hopefully it will go away.

**Comment by tonykakuuu** [comment]
I am now (I wasn't aware this fork existed or that your config files are
related to that). It does build now, even with the encoder definitions as
they were, but the keyboard isn't recognized by either VIAL web or the
dedicated application. This may be a problem with my setup or related to
Helios/rp2040, which I need to rule out first.

**Comment by mohoyt** [comment]
Great! Yeah - vial only works if you compile using vial-qmk. Does the keyboard work with the new vial flashed firmware, but only not get recognised by vial? Just trying to understand where the issue lies.

**Comment by tonykakuuu** [comment]
Thanks, everything works, it was a problem with my build environment after all. If possible, could you add a reference to the vial--qmk fork on the firmware README page? This would perhaps help others in a similar situation.

**Comment by mohoyt** [comment]
No worries - the build envs can be tricky to set up for the first time! Will make a note of it on the read me. ✅
