### ISSUE TITLE
nice!nano

### ISSUE THREAD

**Issue by jonasradke** [mohoyt/lagom#4]
Hey,
How would I get a nice!nano working with this?

**Comment by jonasradke** [comment]
managed to get zmk working based on nibble keyboard config

**Comment by M13G** [comment]
@jonasradke hey man is the firmware available on your github and does the firmware allow you to use your keyboard's functions fully like the oled display and those two rotary encoders?

**Comment by jonasradke** [comment]
Yes you can look at my radiance repository and base ur config of that.

**Comment by fkpwolf** [comment]
@jonasradke I used your firmware in Actions but looks no keyboard appears after flashing. I have [this SuperMini NRF52840](https://github.com/joric/nrfmicro/wiki/Alternatives#supermini-nrf52840). It is said `Works in ZMK as nice_nano_v2`.

**Comment by jonasradke** [comment]
[firmware.zip](https://github.com/user-attachments/files/18520126/firmware.zip)

try using this firmware. Have you looked into zmk Studio? I have not really configured it to work yet but will do in the future when my exams are over. Just message me directly or open an issue on my repo so I can help you better.
