### ISSUE TITLE
Generating Custom UF2 File for RP2040 Pro Micro

### ISSUE THREAD

**Issue by pioz** [mohoyt/lagom#5]
I am currently working on customizing the QMK firmware for a Lagom that utilizes the RP2040 style Pro Micro. However, I've encountered an issue where, after compiling the firmware, I only obtain a `.hex` file. For my keyboard, I require a `.uf2` file which is compatible with the RP2040's bootloader.

Could someone guide me on the necessary changes or steps needed to compile the firmware specifically for generating a `.uf2` file suitable for an RP2040 style Pro Micro? Any advice or direction on this matter would be greatly appreciated as I am unsure of the modifications needed to achieve this.

Thank you in advance for your help and time.

**Comment by mohoyt** [comment]
Absolutely able to help! There are (at least) two ways. The easiest is using the convert feature in QMK: https://docs.qmk.fm/#/feature_converters?id=overview when you compile your firmware and you append a `-e convert_to=XXXX` to the end of the compile command with the rp2040 controller of your choice. 

Another way would be to set up the base keyboard as a rp2040 board (some details here: https://docs.qmk.fm/#/platformdev_rp2040) but I think the first option should be easier and sufficient. 

Let me know how you get on!

**Comment by pioz** [comment]
It would be nice to include this information in the guide for compiling firmware for the RP2040 micro as well. May be in this guide https://github.com/mohoyt/lagom/blob/main/flash_guide.md

**Comment by mohoyt** [comment]
Good idea! Will add that now.

**Comment by mohoyt** [comment]
Done! Updated https://github.com/mohoyt/lagom/blob/main/flash_guide.md and https://github.com/mohoyt/lagom/blob/main/firmware/ with more info about rp2040
