### ISSUE TITLE
Using uf2(rp2040) for nice!nano

### ISSUE THREAD

**Issue by M13G** [mohoyt/lagom#6]
I was wondering if I can use the precompiled uf2 firmware for my nice!nano v2 as well?

**Comment by mohoyt** [comment]
Hey! Unfortunately not. The precompiled firmware files that I have for the Lagom are based on QMK which isn't supported for the wireless capabilities of Nice!Nano. 

To use a Nice!Nano you'll have to build your own firmware using ZMK or BlueMicro. You should be able to use the QMK config as a rough starting point.
